// Uncomment these if you want to remove firebase and add your own custom backend:
// export { useStories } from './local/useStories'
// export { useHomeFeedPosts } from './local/useHomeFeedPosts'
// export { usePostMutations } from './local/usePostMutations'
// export { useStoryMutations } from './local/useStoryMutations'
// export { useCommentMutations } from './local/useCommentMutations'
// export { useComments } from './local/useComments'
// export { usePost } from './local/usePost'
// export { useProfile } from './local/useProfile'
// export { useDiscoverPosts } from './local/useDiscoverPosts'
// export { useHashtagPosts } from './local/useHashtagPosts'


export { useStories } from './aws/useStories'
export { useHomeFeedPosts } from './aws/useHomeFeedPosts'
export { usePostMutations } from './aws/usePostMutations'
export { useStoryMutations } from './aws/useStoryMutations'
export { useCommentMutations } from './aws/useCommentMutations'
export { useComments } from './aws/useComments'
export { usePost } from './aws/usePost'
export { useProfile } from './aws/useProfile'
export { useDiscoverPosts } from './aws/useDiscoverPosts'
export { useHashtagPosts } from './aws/useHashtagPosts'
export { useCustomPosts } from './aws/useCustomPosts' 
